Repository zephyrsoftwares/checkflow, pull requests merged in 2023-11, with the labels that each got.

#3 Release Checkflow v0.1.0
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/custom_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
  .github/workflows/develop.yml
  .github/workflows/main.yml
  .gitignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  postcss.config.js
  public/favicons/android-chrome-192x192.png
  public/favicons/android-chrome-512x512.png
  public/favicons/apple-touch-icon.png
  public/favicons/browserconfig.xml
  public/favicons/favicon-16x16.png
  public/favicons/favicon-32x32.png
  public/favicons/favicon.ico
  public/favicons/mstile-150x150.png
  public/favicons/safari-pinned-tab.svg
  public/favicons/site.webmanifest
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/assets/images/logo.svg
  src/assets/images/text.svg
  src/assets/styles/App.css
  src/assets/styles/index.css
  src/index.js
  src/setupTests.js
  src/tests/App.test.js
  tailwind.config.js
Labels: Release

#8 CF-0003 - firebase connection, new home view, gitignore edited
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/assets/styles/App.css
  src/config/firebase.js
Labels: Config, Firebase

#10 CF-0005 - Ajouter une page de connexion
  src/App.js
  src/assets/images/google_icon.svg
  src/assets/images/logo_centered.svg
  src/components/connexion/button.js
  src/components/connexion/index.js
  src/components/connexion/input.js
  src/components/connexion/label.js
  src/components/navbaritem.js
  src/pages/connexion.js
  src/pages/index.js
Labels: JSX

#11 CF-0006 - Added the firebase connexion feature and private routes
  package.json
  src/App.js
  src/components/PrivateRoute.js
  src/components/connexion/input.js
  src/config/firebase.js
  src/contexts/AuthContext.js
  src/pages/connexion.js
  src/tests/App.test.js
Labels: Auth, Config, Firebase

#12 CF-0007 - Added logout button on the home page
  src/components/searchbar.js
Labels: Auth, JSX

#14 CF-0007 - Adding google auth, navbar user info from firebase, logout button in searchbar
  src/components/navbarmobile.js
  src/components/navbarprofilesection.js
  src/components/navbarweb.js
  src/components/searchbar.js
  src/config/firebase.js
  src/contexts/AuthContext.js
  src/pages/connexion.js
Labels: Auth, Config, Firebase

#16 CF-0009 - Add PrivateRouteConnexion component and update
  src/App.js
  src/components/PrivateRouteConnexion.js
  src/pages/connexion.js
Labels: Config
